### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by a03z** [7hebel/vscode-ext-smooth-ui#1]
hey, any reasons why it might not work? I'm on the latest vsc version

**Comment by 7hebel** [comment]
Hi, You should open the command palette (`ctrl + shift + p`) and run the `Enable Custom css and js` command. 
Then the notification should popup asking You to restart the VSC.

Let me know if it works.

**Comment by a03z** [comment]
nope, still doesn't work

**Comment by a03z** [comment]
my bad, I thought I was on latest version as it didn't show any update available messages, updated it manually and everything works as a charm now

great ext btw!!
